### ISSUE TITLE
Banco de Dados

### ISSUE THREAD

**Issue by 021fneves** [julian-gaitan/E-DUCA#1]
Como faço para instalar?
Não encontrei os dados de SQL.

**Comment by julian-gaitan** [comment]
Acabo de agregar el archivo educa.sql que es la estructura de la base de datos que exporta phpMyAdmin.
También agrego el archivo README.md para dejar claro la intención de este repositorio.
Me avisa si necesita algo más.
Saludos.

Acabei de adicionar o arquivo educa.sql que é a estrutura do banco de dados que o phpMyAdmin exporta.
Também estou adicionando o arquivo README.md para deixar clara a intenção deste repositório.
Deixe-me saber se você precisar de mais alguma coisa.
Saudações.
